from abc import ABC, abstractmethod

class Movable(ABC):
    @abstractmethod
    def move(self): ...

class Refuelable(ABC):
    @abstractmethod
    def refuel(self): ...

class Flyable(ABC):
    @abstractmethod
    def fly(self): ...

class Pedalable(ABC):
    @abstractmethod
    def pedal_harder(self): ...

class GasCar(Movable, Refuelable): ...      
class Bicycle(Movable, Pedalable): ...      
class Drone(Movable, Flyable): ...          